apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  labels:
    app: postgres1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres1
  template:
    metadata:
      labels:
        app: postgres1
    spec:
      containers:
      - name: postgresqldb
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: employeedb 
---
apiVersion: v1
kind: Service
metadata:
  name: app-service
spec:
  selector:
    app: postgres1
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432